language: node_js
node_js: "stable"
before_script: "npm install"
script: "npm test"
after_script: cat ./coverage/lcov.info | coveralls
notifications:
  email:
    recipients:
    - kengji45@gmail.com
    on_success: never
    on_failure: always